### ISSUE TITLE
Gluetool should display evaluation context variables provided by modules in -L listing

### ISSUE THREAD

**Issue by thrix** [gluetool/gluetool#13]
It seems a good idea, so that gluetool would list evaluation context variables exported by modules in some listing.

**Comment by happz** [comment]
That's a very good idea. We already list shared functions of a module, when showing its help - module owner should document those variables in module's docstring, that seems like a good practice - but we also have a option to list just shared functions, listing variables available in eval context would be nice as well. Probably another option? I'd rather avoid adding it to `-l`.

**Comment by happz** [comment]
Implemented in #21
